#!/bin/bash

cd "$(dirname "$0")/.."

function checkout() {
  repo=$1; url=$2;
  if [ ! -d "$repo" ]; then
    git clone "https://github.com/$url" "$repo"
  fi

  pushd "$repo"
  git fetch && git reset --hard HEAD
  popd
}

echo "Getting libs"
libs_to_parse=$(grep '"name":.*?[^\\]",' ./script/search.json | perl -pe 's/"name": "//; s/^"//; s/",$//')
echo $libs_to_parse

for lib in $libs_to_parse; do
    echo $lib
    checkout "examples-full/$lib" "$lib"
done

echo "Getting applications"
applications_to_parse=$(grep '".+"' ./script/applications.json | perl -pe 's/^"//; s/"$//')

for project in $applications_to_parse; do
      echo $project
      checkout "examples-full/$project" "$project"
done

all_examples=$(find examples-full -name '*.elm')
examples_to_parse=$(
  for example in $all_examples; do
    echo $example
  done
)

echo $examples_to_parse

start=`date +%s.%N`
tree_sitter_report=$(echo $examples_to_parse | npx ts-node ./test/diagnostics.ts)
end=`date +%s.%N`

ret_code=$?

echo -e "-----------------------------------------------------------------\n$tree_sitter_report \n -----------------------------------------------------------------\n"

errors=$( echo "$tree_sitter_report" | sed '/^\s*$/d' | wc -l )

skipped=$( echo ${#skipped_files[@]} )
tried_to_parse=$( echo "$examples_to_parse" | wc -w )
parsed=$(bc -l <<< "$tried_to_parse-$errors")
total=$((tried_to_parse+skipped))
percent=$(bc -l <<< "100*$parsed/$total" )
runtime=$( echo "$end - $start" | bc -l )

printf "Successfully parsed %d of %d files (%.2f%%)\nSkipped: %d Failed: %d\nTook: %s\n" $parsed $total $percent $skipped $errors $runtime

exit $ret_code
