name: Test Diagnostics

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install -g elm0190@npm:elm@latest-0.19.0
      - run: npm install -g elm0191@npm:elm@latest-0.19.1
      - run: npm ci
      - run: npm run compile
      - run: node -r ts-node/register --expose-gc ./test/diagnostics.ts
